<?php

namespace Database\Seeders;

use App\Models\Pet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PetBreedsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Dog breeds
        $dogBreeds = [
            [
                'name' => 'Labrador Retriever',
                'size' => 'Large',
                'temperament' => 'Friendly, Active, Outgoing',
                'lifespan' => '10-12',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 5,
                'exerciseNeeds' => 5,
                'grooming' => 2,
                'colors' => ['Yellow', 'Black', 'Chocolate'],
                'description' => 'Labrador Retrievers are one of the most popular dog breeds in the Philippines. They are known for their friendly temperament, intelligence, and versatility. Originally bred as working dogs, they excel in various roles, from family companions to service dogs.',
                'category' => 'dog',
            ],
            [
                'name' => 'Doberman Pinscher',
                'size' => 'Large',
                'temperament' => 'Alert, Loyal, Fearless',
                'lifespan' => '10-13',
                'energy' => 'High',
                'friendliness' => 3,
                'trainability' => 5,
                'exerciseNeeds' => 4,
                'grooming' => 1,
                'colors' => ['Black & Tan', 'Red & Tan', 'Blue', 'Fawn'],
                'description' => 'The Doberman Pinscher is an elegant and muscular breed known for its loyalty and protective nature. Despite their intimidating appearance, well-trained Dobermans are loving family pets that bond closely with their owners.',
                'category' => 'dogs',
            ],
            [
                'name' => 'German Shepherd',
                'size' => 'Large',
                'temperament' => 'Confident, Courageous, Smart',
                'lifespan' => '9-13',
                'energy' => 'High',
                'friendliness' => 4,
                'trainability' => 5,
                'exercise_needs' => 5,
                'grooming' => 3,
                'colors' => ['Black & Tan', 'Black', 'Sable', 'Red & Black'],
                'description' => 'German Shepherds are versatile working dogs originally developed for herding. Their intelligence, trainability, and loyalty make them excellent companions, guard dogs, and service animals. They require mental stimulation and regular exercise to thrive.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Shih Tzu',
                'size' => 'Small',
                'temperament' => 'Affectionate, Outgoing, Playful',
                'lifespan' => '10-16',
                'energy' => 'Medium',
                'friendliness' => 5,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 5,
                'colors' => ['Gold & White', 'Brown & White', 'Black & White', 'Solid'],
                'description' => 'The Shih Tzu is a small, affectionate companion breed with a distinctive flowing coat and friendly personality. Originally bred as palace companions in China, they thrive on human interaction and are well-suited for apartment living.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Golden Retriever',
                'size' => 'Large',
                'temperament' => 'Friendly, Intelligent, Devoted',
                'lifespan' => '10-12',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 5,
                'exercise_needs' => 4,
                'grooming' => 3,
                'colors' => ['Light Golden', 'Golden', 'Dark Golden'],
                'description' => 'Golden Retrievers are known for their friendly, tolerant attitude and are highly regarded as family pets. Intelligent and eager to please, they excel in obedience training and various dog sports. Their beautiful golden coat requires regular grooming.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Dachshund',
                'size' => 'Small',
                'temperament' => 'Clever, Courageous, Lively',
                'lifespan' => '12-16',
                'energy' => 'Medium',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 3,
                'grooming' => 2,
                'colors' => ['Red', 'Black & Tan', 'Chocolate & Tan', 'Dapple'],
                'description' => 'Dachshunds, also known as "wiener dogs," are known for their long bodies, short legs, and determined personalities. Originally bred to hunt badgers, they are brave, sometimes stubborn, and form strong bonds with their families.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Beagle',
                'size' => 'Small to Medium',
                'temperament' => 'Friendly, Curious, Merry',
                'lifespan' => '12-15',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 3,
                'exercise_needs' => 4,
                'grooming' => 2,
                'colors' => ['Tri-color', 'Lemon & White', 'Red & White'],
                'description' => 'Beagles are scent hounds originally bred for tracking game. They are known for their keen sense of smell, friendly nature, and melodious howl. Compact and hardy, they make wonderful family pets but can be independent and sometimes stubborn.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Pug',
                'size' => 'Small',
                'temperament' => 'Charming, Mischievous, Loving',
                'lifespan' => '12-15',
                'energy' => 'Medium',
                'friendliness' => 5,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 3,
                'colors' => ['Fawn', 'Black'],
                'description' => 'Pugs are characterized by their wrinkled face, curled tail, and playful disposition. Despite their small size, they have a robust build and distinctive personality. They are known for their charming and affectionate nature, making them excellent companion dogs.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Poodle',
                'size' => 'Toy, Miniature, Standard',
                'temperament' => 'Intelligent, Active, Alert',
                'lifespan' => '10-18',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 5,
                'exercise_needs' => 4,
                'grooming' => 5,
                'colors' => ['White', 'Black', 'Apricot', 'Silver', 'Cream'],
                'description' => 'Poodles come in three sizes: Standard, Miniature, and Toy. Despite their elegant appearance, they were originally working water retrievers. Highly intelligent and trainable, they excel in various dog sports and are known for their hypoallergenic coat.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Pomeranian',
                'size' => 'Small',
                'temperament' => 'Inquisitive, Bold, Lively',
                'lifespan' => '12-16',
                'energy' => 'Medium',
                'friendliness' => 3,
                'trainability' => 4,
                'exercise_needs' => 2,
                'grooming' => 5,
                'colors' => ['Orange', 'Red', 'Cream', 'Black', 'Brown'],
                'description' => 'Pomeranians are small spitz-type dogs known for their fluffy double coat and fox-like expression. Despite their tiny size, they have big personalities—alert, intelligent, and often quite bold. They make excellent companion dogs for various living situations.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Corgi',
                'size' => 'Small',
                'temperament' => 'Affectionate, Smart, Alert',
                'lifespan' => '12-15',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 4,
                'exercise_needs' => 4,
                'grooming' => 3,
                'colors' => ['Red & White', 'Sable & White', 'Tri-color', 'Fawn'],
                'description' => 'Pembroke Welsh Corgis are low-set herding dogs with fox-like heads, erect ears, and a friendly expression. Despite their short stature, they are sturdy, athletic, and were bred for herding cattle. They are intelligent, trainable, and make loyal family companions.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Dalmatian',
                'size' => 'Medium to Large',
                'temperament' => 'Dignified, Smart, Outgoing',
                'lifespan' => '11-13',
                'energy' => 'Very High',
                'friendliness' => 4,
                'trainability' => 4,
                'exercise_needs' => 5,
                'grooming' => 1,
                'colors' => ['White & Black', 'White & Liver'],
                'description' => 'Dalmatians are distinctively spotted dogs known for their unique coat pattern. Historically associated with firehouses, they are energetic, athletic, and require substantial exercise. Intelligent but sometimes stubborn, they form strong bonds with their families.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Chihuahua',
                'size' => 'Small',
                'temperament' => 'Charming, Graceful, Sassy',
                'lifespan' => '14-16',
                'energy' => 'Medium',
                'friendliness' => 3,
                'trainability' => 3,
                'exercise_needs' => 1,
                'grooming' => 2,
                'colors' => ['Fawn', 'Black', 'Cream', 'Chocolate', 'Mixed'],
                'description' => 'Chihuahuas are the smallest dog breed, known for their big personalities in tiny packages. Despite their size, they are confident, self-reliant, and often form very close bonds with one person. They come in both short and long coat varieties.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Chow Chow',
                'size' => 'Medium',
                'temperament' => 'Dignified, Serious, Aloof',
                'lifespan' => '8-12',
                'energy' => 'Low',
                'friendliness' => 2,
                'trainability' => 2,
                'exercise_needs' => 2,
                'grooming' => 5,
                'colors' => ['Red', 'Black', 'Blue', 'Cream', 'Cinnamon'],
                'description' => 'Chow Chows are distinctive looking dogs with lion-like manes, blue-black tongues, and a dignified, serious demeanor. One of the ancient dog breeds, they are independent, loyal to family but often reserved with strangers, and require early socialization.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Siberian Husky',
                'size' => 'Medium to Large',
                'temperament' => 'Outgoing, Friendly, Mischievous',
                'lifespan' => '12-14',
                'energy' => 'Very High',
                'friendliness' => 5,
                'trainability' => 3,
                'exercise_needs' => 5,
                'grooming' => 3,
                'colors' => ['Black & White', 'Gray & White', 'Red & White', 'Solid White'],
                'description' => 'Siberian Huskies are working sled dogs known for their striking appearance, endurance, and friendly temperament. With their thick coats, erect triangular ears, and distinctive markings, they are both beautiful and athletic, requiring substantial exercise and mental stimulation.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Shiba Inu',
                'size' => 'Small to Medium',
                'temperament' => 'Alert, Active, Attentive',
                'lifespan' => '13-16',
                'energy' => 'Medium',
                'friendliness' => 3,
                'trainability' => 2,
                'exercise_needs' => 3,
                'grooming' => 3,
                'colors' => ['Red', 'Sesame', 'Black & Tan', 'Cream'],
                'description' => 'The Shiba Inu is a spirited, good-natured Japanese breed with a fox-like appearance. Independent and intelligent, they were originally hunting dogs in the mountainous regions of Japan. Despite their small size, they have a bold, confident personality.',
                'category' => 'dogs',
            ],
            [
                'name' => 'French Bulldog',
                'size' => 'Small',
                'temperament' => 'Playful, Adaptable, Smart',
                'lifespan' => '10-12',
                'energy' => 'Medium',
                'friendliness' => 5,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 1,
                'colors' => ['Brindle', 'Fawn', 'Pied', 'Cream'],
                'description' => 'French Bulldogs are compact, muscular dogs with distinctive bat-like ears and an affectionate nature. They adapt well to apartment living and are known for being playful companions. Their short coat is easy to maintain, though they can have health issues related to their flat faces.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Alaskan Malamute',
                'size' => 'Large',
                'temperament' => 'Affectionate, Loyal, Playful',
                'lifespan' => '10-14',
                'energy' => 'High',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 5,
                'grooming' => 4,
                'colors' => ['Gray & White', 'Black & White', 'Sable & White', 'Red & White'],
                'description' => 'Alaskan Malamutes are powerful, heavy-duty sled dogs with a wolf-like appearance. Larger than the Siberian Husky, they were bred for strength rather than speed. Malamutes are friendly, loyal family dogs but can be independent and require consistent training.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Cocker Spaniel',
                'size' => 'Medium',
                'temperament' => 'Gentle, Smart, Happy',
                'lifespan' => '12-15',
                'energy' => 'Medium',
                'friendliness' => 5,
                'trainability' => 4,
                'exercise_needs' => 3,
                'grooming' => 4,
                'colors' => ['Buff', 'Black', 'Parti-color', 'Red'],
                'description' => 'The Cocker Spaniel is known for its beautiful, silky coat and expressive eyes. Originally bred as hunting dogs, they are now popular family companions. They are gentle, affectionate, and eager to please, though their luxurious coat requires regular grooming.',
                'category' => 'dogs',
            ],
            [
                'name' => 'Aspin (Asong Pinoy)',
                'size' => 'Small to Medium',
                'temperament' => 'Loyal, Intelligent, Resilient',
                'lifespan' => '12-18',
                'energy' => 'Medium',
                'friendliness' => 4,
                'trainability' => 4,
                'exercise_needs' => 3,
                'grooming' => 1,
                'colors' => ['Various', 'Brown', 'Black', 'White', 'Spotted'],
                'description' => 'Aspins, or "Asong Pinoy," are the native dogs of the Philippines. These mixed-breed dogs are known for their resilience, intelligence, and loyalty. With natural selection enhancing their health and adaptability to the local climate, they make excellent companions and working dogs.',
                'category' => 'dogs',
            ],
        ];

        // Cat breeds
        $catBreeds = [
            [
                'name' => 'Philippine Shorthair (Puspin)',
                'size' => 'Small to Medium',
                'temperament' => 'Adaptable, Resilient, Intelligent',
                'lifespan' => '12-15',
                'energy' => 'Medium',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 3,
                'grooming' => 1,
                'colors' => ['Various', 'Tabby', 'Black', 'White', 'Calico'],
                'description' => 'The Philippine Shorthair, affectionately known as "Puspin," is the native cat of the Philippines. These mixed-breed cats are highly adaptable, resilient, and have naturally evolved to thrive in the local climate. They make affectionate companions and efficient hunters.',
                'category' => 'cats',
            ],
            [
                'name' => 'Persian Cat',
                'size' => 'Medium',
                'temperament' => 'Sweet, Gentle, Quiet',
                'lifespan' => '12-16',
                'energy' => 'Low',
                'friendliness' => 4,
                'trainability' => 2,
                'exercise_needs' => 1,
                'grooming' => 5,
                'colors' => ['White', 'Blue', 'Black', 'Red', 'Cream', 'Tabby'],
                'description' => 'Persian cats are known for their long, luxurious coats, round faces, and sweet expressions. One of the oldest cat breeds, they have a calm, gentle temperament and prefer quiet environments. Their magnificent coat requires daily grooming to prevent mats and tangles.',
                'category' => 'cats',
            ],
            [
                'name' => 'Siamese',
                'size' => 'Medium',
                'temperament' => 'Talkative, Social, Intelligent',
                'lifespan' => '12-15',
                'energy' => 'High',
                'friendliness' => 5,
                'trainability' => 5,
                'exercise_needs' => 4,
                'grooming' => 1,
                'colors' => ['Seal Point', 'Blue Point', 'Chocolate Point', 'Lilac Point'],
                'description' => 'Siamese cats are distinctive for their sleek bodies, color points, and striking blue eyes. Known for their intelligence and vocal nature, they form strong bonds with their humans and are often described as "dog-like" in their loyalty and sociability.',
                'category' => 'cats',
            ],
            [
                'name' => 'Himalayan',
                'size' => 'Medium to Large',
                'temperament' => 'Gentle, Calm, Playful',
                'lifespan' => '9-15',
                'energy' => 'Medium',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 5,
                'colors' => ['Seal Point', 'Blue Point', 'Chocolate Point', 'Flame Point'],
                'description' => 'Himalayans are a cross between Persian and Siamese cats, combining the Persian\'s long coat and sweet temperament with the Siamese\'s colorpoint pattern. They are gentle, affectionate companions who enjoy playtime but also appreciate quiet lounging. Their luxurious coat requires regular grooming.',
                'category' => 'cats',
            ],
            [
                'name' => 'Russian Blue',
                'size' => 'Medium',
                'temperament' => 'Reserved, Intelligent, Gentle',
                'lifespan' => '15-20',
                'energy' => 'Medium',
                'friendliness' => 3,
                'trainability' => 4,
                'exercise_needs' => 2,
                'grooming' => 2,
                'colors' => ['Blue'],
                'description' => 'Russian Blues are elegant cats with a plush, silvery-blue coat and emerald green eyes. They are known for their intelligence, gentle temperament, and somewhat reserved nature with strangers. Once bonded, they are deeply loyal to their families and often get along well with other pets.',
                'category' => 'cats',
            ],
            [
                'name' => 'American Shorthair',
                'size' => 'Medium to Large',
                'temperament' => 'Easy-going, Independent, Affectionate',
                'lifespan' => '15-20',
                'energy' => 'Medium',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 3,
                'grooming' => 2,
                'colors' => ['Silver Tabby', 'Brown Tabby', 'Black', 'White', 'Bi-color'],
                'description' => 'American Shorthairs are sturdy, adaptable cats descended from European cats brought to America to control rodents. They are known for their easy-going nature, hunting prowess, and adaptability. With moderate exercise needs and minimal grooming requirements, they make excellent family pets.',
                'category' => 'cats',
            ],
            [
                'name' => 'Exotic Shorthair',
                'size' => 'Medium',
                'temperament' => 'Gentle, Calm, Playful',
                'lifespan' => '12-15',
                'energy' => 'Low to Medium',
                'friendliness' => 4,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 3,
                'colors' => ['White', 'Black', 'Blue', 'Red', 'Cream', 'Tabby', 'Bi-color'],
                'description' => 'Often called "the lazy man\'s Persian," Exotic Shorthairs have the Persian\'s sweet face and personality but with a short, plush coat that requires less grooming. They are gentle, calm companions who enjoy playing but are also content to lounge around the house.',
                'category' => 'cats',
            ],
            [
                'name' => 'Bengal',
                'size' => 'Medium to Large',
                'temperament' => 'Active, Intelligent, Playful',
                'lifespan' => '12-16',
                'energy' => 'Very High',
                'friendliness' => 4,
                'trainability' => 5,
                'exercise_needs' => 5,
                'grooming' => 1,
                'colors' => ['Brown Spotted', 'Snow Spotted', 'Silver Spotted', 'Marble Pattern'],
                'description' => 'Bengal cats are known for their wild appearance with distinctive spotted or marbled coat patterns. These active, athletic cats have a playful, energetic nature and high intelligence. They often enjoy water, can learn tricks, and need substantial environmental enrichment to stay happy and healthy.',
                'category' => 'cats',
            ],
            [
                'name' => 'British Shorthair',
                'size' => 'Medium to Large',
                'temperament' => 'Easygoing, Reserved, Loyal',
                'lifespan' => '12-17',
                'energy' => 'Low to Medium',
                'friendliness' => 3,
                'trainability' => 3,
                'exercise_needs' => 2,
                'grooming' => 2,
                'colors' => ['Blue', 'Black', 'White', 'Red', 'Cream', 'Tabby'],
                'description' => 'British Shorthairs are known for their dense, plush coat and round face with characteristic "Cheshire cat" smile. They have a calm, undemanding nature and quiet voice. While not overly demonstrative, they are loyal companions who prefer to be near their humans without demanding constant attention.',
                'category' => 'cats',
            ],
            [
                'name' => 'American Curl',
                'size' => 'Small to Medium',
                'temperament' => 'Curious, People-oriented, Playful',
                'lifespan' => '12-16',
                'energy' => 'Medium',
                'friendliness' => 5,
                'trainability' => 4,
                'exercise_needs' => 3,
                'grooming' => 2,
                'colors' => ['Various', 'Tabby', 'Solid', 'Bi-color', 'Pointed'],
                'description' => 'American Curls are distinguished by their unique ears that curl backward away from the face. These cats remain playful throughout their lives and are known for their people-oriented, affectionate nature. They adapt well to various living situations and get along well with children and other pets.',
                'category' => 'cats',
            ],
        ];

        // Insert dog breeds
        foreach ($dogBreeds as $breed) {
            Pet::firstOrCreate(
                ['name' => $breed['name']],
                array_merge(
                    $breed,
                    ['slug' => Str::slug($breed['name'])]
                )
            );
        }

        // Insert cat breeds
        foreach ($catBreeds as $breed) {
            Pet::firstOrCreate(
                ['name' => $breed['name']],
                array_merge(
                    $breed,
                    ['slug' => Str::slug($breed['name'])]
                )
            );
        }
    }
}
