[nixpacks]
php-version = "8.2"
php-extensions = ["intl", "zip"]

[phases.setup]
nixPkgs = ["icu", "zlib", "libzip", "pkg-config"]

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y libicu-dev libzip-dev"
]

[phases.build]
cmds = [
  "docker-php-ext-configure intl",
  "docker-php-ext-install intl zip",
  "composer install --optimize-autoloader --no-dev --no-interaction",
  "chmod +x railway-deploy.sh",
  "chmod +x debug-railway.sh",
  "./railway-deploy.sh"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"